In [342]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

Load the Data

In [343]:
data = pd.read_csv('Churn_Modelling.csv')

In [344]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

Drop Irrelevant Data

In [345]:
data = data.drop(['RowNumber','CustomerId', 'Surname'], axis=1)

In [346]:
data.head(2)

CreditScore Geography  Gender  Age  Tenure   Balance  NumOfProducts  \
0          619    France  Female   42       2      0.00              1   
1          608     Spain  Female   41       1  83807.86              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0

Encoding
LabelEncoder: Categorical to numerical.
Better whene categories are small (2/3)

In [297]:
LabelEncoder_gender = LabelEncoder()

In [347]:
data['Gender'] = LabelEncoder_gender.fit_transform(data['Gender'])

In [349]:
data.head(6)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       0   42       2       0.00              1   
1          608     Spain       0   41       1   83807.86              1   
2          502    France       0   42       8  159660.80              3   
3          699    France       0   39       1       0.00              2   
4          850     Spain       0   43       2  125510.82              1   
5          645     Spain       1   44       8  113755.78              2   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0  
5          1               0        149756.71       1

One Hot Encoder

In [351]:
from sklearn.preprocessing import OneHotEncoder

In [352]:
OneHotEncoder_geo = OneHotEncoder()

In [360]:
print(OneHotEncoder_geo)

OneHotEncoder()


In [355]:
geo_OneHotEncoder = OneHotEncoder_geo.fit_transform(data[['Geography']]).toarray()

In [303]:
type(geo_OneHotEncoder)

numpy.ndarray

In [ ]:
data['Gender'].head()#Maintain a pandas series

In [ ]:
data[['Gender']].head() #Maintain a pandas DataFrane

In [359]:
print(geo_OneHotEncoder)

[[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 ...
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


Get the Features Names

In [356]:
columns = OneHotEncoder_geo.get_feature_names_out(['Geography'])
#To get the feature names, instance (OneHotEncoder_geo) will be used

In [358]:
print(columns)

['Geography_France' 'Geography_Germany' 'Geography_Spain']


In [309]:
type(geo_OneHotEncoder)

numpy.ndarray

In [361]:
geo_OneHotEncoder_df = pd.DataFrame(geo_OneHotEncoder, columns=OneHotEncoder_geo.get_feature_names_out(['Geography']))

In [363]:
print(geo_OneHotEncoder_df.head())

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0


Concate the dataframes

In [366]:
data = pd.concat([data.drop('Geography', axis=1), geo_OneHotEncoder_df], axis=1)

In [367]:
data.head(3)

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1               1.0   
1               1        112542.58       0               0.0   
2               0        113931.57       1               1.0   

   Geography_Germany  Geography_Spain  
0                0.0              0.0  
1                0.0              1.0  
2                0.0              0.0

In [368]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   CreditScore        10000 non-null  int64  
 1   Gender             10000 non-null  int32  
 2   Age                10000 non-null  int64  
 3   Tenure             10000 non-null  int64  
 4   Balance            10000 non-null  float64
 5   NumOfProducts      10000 non-null  int64  
 6   HasCrCard          10000 non-null  int64  
 7   IsActiveMember     10000 non-null  int64  
 8   EstimatedSalary    10000 non-null  float64
 9   Exited             10000 non-null  int64  
 10  Geography_France   10000 non-null  float64
 11  Geography_Germany  10000 non-null  float64
 12  Geography_Spain    10000 non-null  float64
dtypes: float64(5), int32(1), int64(7)
memory usage: 976.7 KB


In [370]:
with open('LabelEncoder_gender.pkl', 'wb') as file: #LabelEncoder_Gender: instance name
    pickle.dump(LabelEncoder_gender, file)

In [371]:
with open('OneHotEncoder_geo.pkl', 'wb') as file: #OneHotEncoder_geo: instance name
    pickle.dump(OneHotEncoder_geo, file)

In [372]:
data.head(3)

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1               1.0   
1               1        112542.58       0               0.0   
2               0        113931.57       1               1.0   

   Geography_Germany  Geography_Spain  
0                0.0              0.0  
1                0.0              1.0  
2                0.0              0.0

In [373]:
X = data.drop('Exited', axis=1)

In [374]:
X.head(3)

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1        101348.88               1.0                0.0   
1               1        112542.58               0.0                0.0   
2               0        113931.57               1.0                0.0   

   Geography_Spain  
0              0.0  
1              1.0  
2              0.0

In [375]:
y = data['Exited']

In [377]:
y.head(3)

0    1
1    0
2    1
Name: Exited, dtype: int64

Split into dependent and independent features

In [378]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [381]:
X_train.shape, X_test.shape

((8000, 12), (2000, 12))

In [382]:
y_train.shape, y_test.shape

((8000,), (2000,))

Scaling the features

In [ ]:
#A preprocessing tool in scikit-learn that standardizes features by removing the mean and scaling to unit variance.
scaler = StandardScaler()

In [383]:
#The result is a standardized version of X_train where each feature has a mean of 0 and a standard deviation of 1.
X_train = scaler.fit_transform(X_train)

In [384]:
#Uses the μμ and σσ calculated from the training data (fit step) to standardize the test dataset (X_test).
X_test = scaler.transform(X_test)

In [386]:
type(X_train)

numpy.ndarray

In [389]:
X_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [390]:
y_train

9254    0
1561    0
1670    1
6087    1
6669    1
       ..
5734    0
5191    0
5390    1
860     1
7270    0
Name: Exited, Length: 8000, dtype: int64

In [392]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

## ANN Implementation 

In [393]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

Number of input layer neurons

In [394]:
(X_train.shape[1], )

(12,)

## Build Our ANN Model

In [396]:
model = Sequential([
    
    Dense(64, activation='relu', input_shape = (X_train.shape[1], )), #1st HL
    Dense(32, activation='relu'), #2nd HL
    Dense(1, activation='sigmoid')
    
    ])

In [397]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_9 (Dense)             (None, 64)                832       
                                                                 
 dense_10 (Dense)            (None, 32)                2080      
                                                                 
 dense_11 (Dense)            (None, 1)                 33        
                                                                 
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


Compile the model

In [398]:
import tensorflow
optim = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()

In [399]:
model.compile(optimizer=optim, loss=loss, metrics=['accuracy'])

## Set TensorBoard

In [400]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

In [401]:
log_dir = "logs/fit"

In [402]:
tensorflow_callbacks = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [403]:
EarlyStopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

## Train the Model

In [404]:
history = model.fit(

    X_train, y_train, validation_data = (X_test, y_test), epochs=100, 
    callbacks = [tensorflow_callbacks, EarlyStopping_callback]
)

Epoch 1/100
250/250 [==============================] - 2s 5ms/step - loss: 0.4006 - accuracy: 0.8366 - val_loss: 0.3497 - val_accuracy: 0.8590
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3596 - accuracy: 0.8528 - val_loss: 0.3526 - val_accuracy: 0.8560
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3464 - accuracy: 0.8564 - val_loss: 0.3578 - val_accuracy: 0.8495
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3459 - accuracy: 0.8560 - val_loss: 0.3504 - val_accuracy: 0.8575
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3419 - accuracy: 0.8577 - val_loss: 0.3423 - val_accuracy: 0.8620
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3394 - accuracy: 0.8625 - val_loss: 0.3577 - val_accuracy: 0.8605
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3344 - accuracy: 0.8640 - val_loss: 0.3409 - val_accuracy: 0.8560

In [405]:
model.save('model.h5')

d:\Python\Deep Learning\ann\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(
